Feature/category pages
Pak-Thani/consumer-app pull request #37
Opened 2022-11-07 12:48 UTC by Aryanda04

## Issue / Task

## Summary

## Test Plan

2022-11-07 15:13 UTC, muhammadhafizm reviewed
format file `public/images/newlogo.PNG`, pake `.png` kalau ga nanti ga kebaca sama config.js

2022-11-07 15:13 UTC, muhammadhafizm commented on pages/index.js
> +  console.log(allCustomSectionData);
hapus bagian debug sebelum masuk staging.

2022-11-07 15:13 UTC, muhammadhafizm commented on pages/index.js
> +  console.log(customSections);
hapus bagian debug sebelum masuk staging

2022-11-07 15:13 UTC, muhammadhafizm commented on pages/category/index.module.css
> +    /* margin: 0 auto; */
delete this unrelated comment

2022-11-07 15:13 UTC, muhammadhafizm commented on pages/category/index.js
> +  // console.log(categorySlug)
delete this comment

2022-11-07 15:13 UTC, muhammadhafizm commented on components/ProductCards/index.js
> +      <div className={`${styles.cardBottomSection} `}>
kenapa harus di guard dalam bentuk string ya? `${``}` apakah perlu?

2022-11-10 06:19 UTC, manokrajin approved these changes

2022-11-10 06:23 UTC, manokrajin requested changes
alt di image icon category dihapus aja ya, pas lagi skeleton view dia malah keliatan alt nya 
![image](https://user-images.githubusercontent.com/67569896/201015810-ef2f840f-ddbb-43ce-8b1c-eed2723fc36b.png)

2022-11-10 06:23 UTC, manokrajin commented
> alt di image icon category dihapus aja ya, pas lagi skeleton view dia malah keliatan alt nya ![image](https://user-images.githubusercontent.com/67569896/201015810-ef2f840f-ddbb-43ce-8b1c-eed2723fc36b.png)

eh itu karena gambarnya gaada ya. tapi better dihapus aja ya. takut meledak

2022-11-10 06:43 UTC, Aryanda04 commented
> alt di image icon category dihapus aja ya, pas lagi skeleton view dia malah keliatan alt nya

alt image itu muncul kalau gagal ngeload gambar. gak gnaruh sama skeleton nya

2022-11-10 06:49 UTC, manokrajin commented
> > alt di image icon category dihapus aja ya, pas lagi skeleton view dia malah keliatan alt nya
> 
> alt image itu muncul kalau gagal ngeload gambar. gak ngaruh sama skeleton nya
> 
> mau tetep dihapus?

hapus, jadi jelek tar skeletonnya. masa user liat icon image

2022-11-11 12:25 UTC, manokrajin approved these changes

2022-11-11 12:25 UTC, merged