feature/animation-caraousel
Pak-Thani/consumer-app pull request #46
Opened 2022-12-07 18:24 UTC by Angelloey

## Issue / Task

- [x]  Skeleton View on Banner / Carousel
- [ ]   Swipe Animation on Banner / Carousel
- [x]  Set Timeout on Banner / Carousel

## Summary

- Add new logic Caraousel animation
- Add Skeleton Caraousel

## Test Plan

https://user-images.githubusercontent.com/75886889/203280058-1bf10a58-005a-4c23-bc66-12cec6392fc9.mp4

2022-12-07 20:55 UTC, manokrajin requested changes
![image](https://user-images.githubusercontent.com/67569896/206292740-148af271-8f1d-4e40-8fe5-328d3eddcb33.png)

- arrow nya diubah jadi warna putih, much better kalo kamu bisa buat kayak tombol kembali pada detail produk, yang bentuknya bener bener button, ini contohnya
![image](https://user-images.githubusercontent.com/67569896/206293080-89ff0940-e24a-483d-841f-a0ef9b0e5e45.png)

- animasi dan button udah work, kalo bisa di disable gerakan swipe pada versi dekstop, jadi gerakan swipe pada banner hanya muncul pada versi mobile -> iniatiative saja, prioritasin poin pertama

button jangan kegedean, ganyaman dilihat.

2022-12-07 20:56 UTC, manokrajin commented
> ![image](https://user-images.githubusercontent.com/67569896/206292740-148af271-8f1d-4e40-8fe5-328d3eddcb33.png)
> 
> * arrow nya diubah jadi warna putih, much better kalo kamu bisa buat kayak tombol kembali pada detail produk, yang bentuknya bener bener button, ini contohnya
>   ![image](https://user-images.githubusercontent.com/67569896/206293080-89ff0940-e24a-483d-841f-a0ef9b0e5e45.png)
> * animasi dan button udah work, kalo bisa di disable gerakan swipe pada versi dekstop, jadi gerakan swipe pada banner hanya muncul pada versi mobile -> iniatiative saja, prioritasin poin pertama
> 
> button jangan kegedean, ganyaman dilihat.

kenapa lebih bagus pake button kayak di detail produk? supaya button tidak nyaru dengan banner yang akan diupload nantinya

2022-12-07 20:57 UTC, manokrajin commented
akhirnya bisa di deploy 👍

2022-12-16 05:12 UTC, Angelloey commented
hilang arrownya :)

> > ![image](https://user-images.githubusercontent.com/67569896/206292740-148af271-8f1d-4e40-8fe5-328d3eddcb33.png)
> > 
> > * arrow nya diubah jadi warna putih, much better kalo kamu bisa buat kayak tombol kembali pada detail produk, yang bentuknya bener bener button, ini contohnya
> >   ![image](https://user-images.githubusercontent.com/67569896/206293080-89ff0940-e24a-483d-841f-a0ef9b0e5e45.png)
> > * animasi dan button udah work, kalo bisa di disable gerakan swipe pada versi dekstop, jadi gerakan swipe pada banner hanya muncul pada versi mobile -> iniatiative saja, prioritasin poin pertama
> > 
> > button jangan kegedean, ganyaman dilihat.
> 
> kenapa lebih bagus pake button kayak di detail produk? supaya button tidak nyaru dengan banner yang akan diupload nantinya

hilang arrownya bang

2022-12-27 16:33 UTC, closed without merging